//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naviam.WebUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Naviam.WebUI.Resources.Mails", typeof(Mails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///Thank you for registering on Naviam. Your sign-in email address has now been updated.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///Your registration code is: {1}
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///&lt;b&gt;
        ///Please reconfirm your email by &lt;a target=&quot;_blank&quot; href=&quot;{0}&quot;&gt;clicking here&lt;/a&gt;
        ///&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///Alternatively, paste {0} into your browser address window to confirm that this is your email address.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///To log on to The Naviam visit the homepage http://www.naviam.com
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///Thanks again,
        ///&lt;br&gt;
        ///The Naviam Team.
        /// </summary>
        public static string ConfirmationMail {
            get {
                return ResourceManager.GetString("ConfirmationMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation of registration on Naviam.
        /// </summary>
        public static string ConfirmationMailSubject {
            get {
                return ResourceManager.GetString("ConfirmationMailSubject", resourceCulture);
            }
        }
    }
}
