-- =============================================
-- Script Template
-- =============================================
USE [naviam]
GO
SET IDENTITY_INSERT [dbo].[categories] ON
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (1, N'Auto&Transport', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (2, N'Bills&Utilities', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (3, N'Business Services', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (4, N'Education', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (5, N'Entartainment', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (6, N'Fees&Charges', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (7, N'Financial', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (8, N'Food&Dining', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (9, N'Gifts&Donations', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (10, N'Health&Fitness', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (11, N'Home', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (12, N'Income', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (13, N'Kids', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (14, N'Personal Care', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (15, N'Pets', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (16, N'Shopping', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (17, N'Taxes', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (18, N'Transfer', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (19, N'Travel', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (20, N'Uncategorized', NULL, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (21, N'Auto Insuarence', 1, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (22, N'Auto Payment', 1, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (23, N'Gas & Fuel', 1, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (24, N'Parking', 1, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (25, N'Public Transportation', 1, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (26, N'Service & Parts', 1, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (27, N'Home Phone', 2, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (28, N'Internet', 2, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (29, N'Mobile Phone', 2, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (30, N'Television', 2, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (31, N'Utilities', 2, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (32, N'Advertising', 3, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (33, N'Legal', 3, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (34, N'Office Supplies', 3, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (35, N'Printing', 3, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (36, N'Shipping', 3, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (37, N'Books & Supplies', 4, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (38, N'Student Loan', 4, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (39, N'Tuition', 4, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (40, N'Amusement', 5, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (41, N'Arts', 5, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (42, N'Movies & DVDs', 5, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (43, N'Music', 5, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (44, N'Newspapers & Magazines', 5, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (45, N'ATM Fee', 6, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (46, N'Bank Fee', 6, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (47, N'Finance Charge', 6, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (48, N'Late Fee', 6, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (49, N'Service Fee', 6, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (50, N'Trade Commissions', 6, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (51, N'Financial Advisor', 7, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (52, N'Life Insurance', 7, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (53, N'Alcohol & Bars', 8, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (54, N'Coffee Shops', 8, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (55, N'Fast Food', 8, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (56, N'Groceries', 8, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (57, N'Restaurants', 8, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (58, N'Charity', 9, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (59, N'Gift', 9, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (60, N'Dentist', 10, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (61, N'Doctor', 10, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (62, N'Eyecare', 10, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (63, N'Gym', 10, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (64, N'Health Insurance', 10, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (65, N'Pharmacy', 10, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (66, N'Sports', 10, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (67, N'Furnishings', 11, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (68, N'Home Improvement', 11, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (69, N'Home Insurance', 11, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (70, N'Home Services', 11, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (71, N'Home Supplies', 11, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (72, N'Lawn & Garden', 11, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (73, N'Mortgage & Rent', 11, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (74, N'Bonus', 12, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (75, N'Interest Income', 12, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (76, N'Paycheck', 12, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (77, N'Reimbursement', 12, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (78, N'Rental Income', 12, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (79, N'Returned Purchase', 12, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (80, N'Allowance', 13, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (81, N'Baby Supplies', 13, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (82, N'Babysitter & Daycare', 13, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (83, N'Child Support', 13, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (84, N'Kids Activities', 13, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (85, N'Toys', 13, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (86, N'Hair', 14, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (87, N'Laundry', 14, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (88, N'Spa & Massage', 14, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (89, N'Pet Food & Supplies', 15, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (90, N'Pet Grooming', 15, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (91, N'Veterinary', 15, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (92, N'Books', 16, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (93, N'Clothing', 16, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (94, N'Electronics & Software', 16, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (95, N'Hobbies', 16, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (96, N'Sporting Goods', 16, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (97, N'Federal Tax', 17, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (98, N'Local Tax', 17, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (99, N'Property Tax', 17, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (100, N'Sales Tax', 17, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (101, N'State Tax', 17, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (102, N'Credit Card Payment', 18, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (103, N'Transfer for Cash Spending', 18, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (104, N'Air Travel', 19, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (105, N'Hotel', 19, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (106, N'Rental Car & Taxi', 19, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (107, N'Vacation', 19, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (108, N'Cash & ATM', 20, NULL)
INSERT [dbo].[categories] ([id], [name], [parent_id], [id_user]) VALUES (109, N'Check', 20, NULL)
SET IDENTITY_INSERT [dbo].[categories] OFF
